- name: Gather file info
  integrity_stats:
    directories:
      - /opt
      # - /lib
      # - /lib64
      - /etc
      # - /boot
      # - /bin
      # - /sbin
      # - /srv
      # - /home
      - /var/www
      - /var/local
      - /var/snap
      - /var/lib
      # - /root
    service_host: "127.0.0.1"
    service_port: 6060
  become: true