---
- name: Get directory tree
  find:
    paths:
      - /home
      - /opt
      - /lib
      - /lib64
      - /dev
      - /etc
      - /boot
      - /bin
      - /sbin
      - /srv
      - /var
      - /root
    recurse: yes
    depth: 4
    file_type: directory
  register: dir_list
  become: true

- name: Gather file info
  integrity_stats:
    dirs: "{{ dir_list }}"
    service_host: "127.0.0.1"
    service_port: 8000
  become: true
