---
- name: Get files 
  find:
    paths:
      - /home
      - /opt
      - /lib
      - /lib64
      - /dev
      - /etc
      - /boot
      - /bin
      - /sbin
      - /srv
      - /var
      - /root
    recurse: yes
    file_type: file
    exclude:
      - "*.gz"
      - "*.zip"
      - "*.tar"
      - "*.rar"
      - "*.mnt"
  register: file_list
  become: yes

- debug:
    var: "{{ file_list.files | length }}"

- name: Gather file info
  integrity_stats:
    files: "{{ file_list.files | map(attribute='path') | list }}"
  become: yes
  register: file_details

- name: Export file details
  delegate_to: localhost
  copy:
    content: "{{ file_details.result | to_nice_json }}"
    dest: "/tmp/sys_check/results/files_details/{{ ansible_facts.default_ipv4.address }}.json"
