- name: Install pip
  raw: sudo apt-get install -y python3-pip

- name: Install requests module
  pip:
    name: requests
    state: present
- name: Gather file info
  integrity_stats:
    directories:
      # - /opt
      # - /lib
      # - /lib64
      # - /etc
      # - /boot
      # - /bin
      # - /sbin
      # - /srv
      - /home
      # - /var/www
      # - /var/local
      # - /var/snap
      # - /var/lib
      # - /root
    service_host: "192.168.136.133"
    service_port: 6969
  become: true