- name: Gather file info
  integrity_stats:
    directories:
      # - /opt
      # - /lib
      # - /lib64
      - /etc
      # - /boot
      # - /bin
      # - /sbin
      # - /srv
      # - /var
      # - /root
    service_host: "127.0.0.1"
    service_port: 6969
  become: true